binary_sensor:
  - platform: template
    sensors:
      dogs_fed:
        unique_id: "dogs_fed"
        friendly_name: "Dogs Have Been Fed"
        value_template: >
          {% set sensor = namespace(state=false) %}
          {% set breakfast_start = now().strftime("%Y-%m-%d 05:00") | as_datetime %}
          {% set breakfast_end = now().strftime("%Y-%m-%d 12:00") | as_datetime %}
          {% set dinner_start = now().strftime("%Y-%m-%d 17:00") | as_datetime %}
          {% set dinner_end = now().strftime("%Y-%m-%d 23:59:59") | as_datetime %}
          {% set dinner_start_yesterday = as_local(((dinner_start | as_timestamp) - 86400) | as_datetime).strftime("%Y-%m-%d %H:%M:%S") | as_datetime %}
          {% set dinner_end_yesterday = as_local(((dinner_end | as_timestamp) - 86400) | as_datetime).strftime("%Y-%m-%d %H:%M:%S") | as_datetime %}
          {% set midnight = now().strftime("%Y-%m-%d 00:00") | as_datetime %}
          {% set last_changed = states("input_datetime.last_time_dogfood_open") | as_datetime %}
          {% set current_time = as_local(now()).strftime("%Y-%m-%d %H:%M") | as_datetime %}

          {# Check if time is between breakfast_start and dinner_start #}
          {# Dogs are fed if they were given breakfast #}
          {% if breakfast_start <= current_time <= dinner_start %}
            {% if breakfast_start <= last_changed <= breakfast_end  %}
                {% set sensor.state = true %}
            {% endif %}          
          {# Check if time is between dinner_start and midnight #}
          {# Dogs are fed if they were given dinner #}
          {% elif dinner_start <= current_time <= dinner_end %}
            {% if dinner_start <= last_changed <= dinner_end %}
                {% set sensor.state = true %}
            {% endif %}
          {# Check if time is between midnight and breakfast_start #}            
          {# Dogs are fed if they were given dinner yesterday #}
          {% elif midnight <= current_time <= breakfast_start %}
            {% if dinner_start_yesterday <= last_changed <= dinner_end_yesterday %}
                {% set sensor.state = true %}
            {% endif %}
          {% endif %}
          {{ sensor.state }}
