mqtt:
  broker: !secret mqtt_broker

###### Add all the motion sensors ######
binary_sensor:
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/25410"
    name: "Master Bathroom Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 156
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/3171229"
    name: "Toilet Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 1
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/4814"
    name: "Upstairs Back Stairs Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 204
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/20078"
    name: "Downstairs Back Stairs Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 28
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/2074077"
    name: "Master Bedroom Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 1
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/25771"
    name: "Entry Hallway Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 92
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/17137"
    name: "Outside Powder Room Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 172
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/21469"
    name: "Inside Powder Room Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 188
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/2267069"
    name: "Laundry Room Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 1
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/2012701"
    name: "Kitchen Desk Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 1
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/5932"
    name: "Downstairs Playroom Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 28
    force_update: true
    off_delay: 1
    device_class: motion
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/7255"
    name: "Garage Motion"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 172
    force_update: true
    off_delay: 1
    device_class: motion

  ###### Add trends for these sensors ######
  - platform: trend
    sensors:
      master_bathroom_temp_rising:
        entity_id: sensor.master_bathroom_temperature
        sample_duration: 300
        max_samples: 50
        min_gradient: 0.0008
      master_bathroom_humidity_rising:
        entity_id: sensor.master_bathroom_humidity
        sample_duration: 300
        max_samples: 50
        min_gradient: 0.0008

  ###### Add RTL_433 script error sensor ######
  - platform: mqtt
    qos: 1
    state_topic: "home-assistant/sensors/rtl_error"
    name: "RTL Error"
    value_template: >
      {{ value_json.cmd }}
    payload_on: 911
    payload_off: 411
    device_class: problem

###### Add the Accurite temperature/humidity and Bed sensors ######
sensor:
  - platform: mqtt
    state_topic: "home-assistant/sensors/2966"
    device_class: temperature
    name: "Dryer Temperature"
    value_template: >
      {{ value_json.temperature_C | float }}
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home-assistant/sensors/2966"
    device_class: humidity
    name: "Dryer Humidity"
    value_template: >
      {{ value_json.humidity | float }}
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home-assistant/sensors/matt_bed"
    name: "Matt Bed Presence"
    value_template: >
      {{ value_json.pressure | float }}
  - platform: mqtt
    state_topic: "home-assistant/sensors/julie_bed"
    name: "Julie Bed Presence"
    value_template: >
      {{ value_json.pressure | float }}
