- platform: mqtt
  name: Laundry Room Lights
  payload_on: "on"
  payload_off: "off"
  qos: 0
  state_topic: shellies/shelly1-E8DB84D46C27/relay/0
  command_topic: shellies/shelly1-E8DB84D46C27/relay/0/command
  json_attributes_topic: shellies/shelly1-E8DB84D46C27/info
  icon: mdi:lightbulb